FROM ubuntu:18.04
RUN apt update 
RUN apt install curl -y && apt install git -y
COPY build.sh .
COPY BP-BASE-SHELL-STEPS .
RUN chmod +x build.sh
ENV ACTIVITY_SUB_TASK_CODE BP-GIT-REPO-DELETE-BRANCHS-TASK
ENV SLEEP_DURATION 5s
ENV VALIDATION_FAILURE_ACTION WARNING
ENV FILE ""
ENV ORGANISATION ""
ENV RETENION_TIME ""
ENTRYPOINT [ "./build.sh" ]
